import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "../styles/globals.scss";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Charleston Pride",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={openSans.className}>{children}</body>
    </html>
  );
}
