name: Azure Static Web Apps CI/CD (Preview)

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: preview-deploy
  cancel-in-progress: true

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Preview
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_GLACIER_0B8F1C80F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/web"
          api_location: ""
          output_location: "build"
        env:
          NEXT_PUBLIC_PREVIEW_MODE: "true"
          NEXT_PUBLIC_SANITY_API_READ_TOKEN: ${{ secrets.SANITY_API_READ_TOKEN }}
